### ISSUE TITLE
npm run build webpack error

### ISSUE THREAD

**Issue by dudunegrinhu** [yii2-starter-kit/yii2-starter-kit#646]
I'm following the installation steps and when I do the last step "npm run build" I get this error

`npm run build

> @ build /var/www/html/
> webpack --progress

  0% compiling(node:14817) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 10% building modules 0/2 modules 2 active ...tml/frontend/web/css/style.less(node:14817) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
 77% module and chunk tree optimization unnamed compat plugin/var/www/html/node_modules/webpack/lib/Chunk.js:846
		throw new Error(
		^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/var/www/html/node_modules/webpack/lib/Chunk.js:846:9)
    at /var/www/html/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /var/www/html/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/html/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/var/www/html/adrsnow/node_modules/webpack/lib/Compilation.js:1231:27)
    at hooks.make.callAsync.err (/var/www/html/node_modules/webpack/lib/Compiler.js:546:17)
    at _done (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err1 (eval at create (/var/www/html/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:32:22)
    at _addModuleChain (/var/www/html/node_modules/webpack/lib/Compilation.js:1082:12)
    at processModuleDependencies.err (/var/www/html/node_modules/webpack/lib/Compilation.js:998:9)
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `webpack --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-11-04T14_38_14_725Z-debug.log`

**Comment by XzAeRo** [comment]
This is the same issue as described in #636

**Comment by dudunegrinhu** [comment]
it works, thanks @XzAeRo
